[package]
name = "kvm_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util"] }
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
rdev = "0.5"
kvm_core = { path = "../core" }
futures = "0.3"
